### ISSUE TITLE
The "Download Runtime..." form can be submitted (OK button) with empty dropdown menu

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-rsp#42] opened 2020-11-06 08:21 UTC
- Download server -> select JBoss Data Virtualization (any version) -> OK -> nothing happens

**Comment by robstryker** [comment] 2020-11-11 20:56
Duplicate of https://github.com/redhat-developer/intellij-rsp/issues/26

**Closed as completed by robstryker** 2020-11-11 20:56 UTC
