### ISSUE TITLE
IOException when starting server

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/intellij-rsp#23] opened 2020-11-06 07:34 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 
- IntelliJ version: 2018.3
- Intellij-rsp extension version master

## What did you run exactly?
Download RH RSP -> Download WF 21 -> Start WF 21 (run)

## Actual behavior
No output from server, exceptions in log.

## Expected behavior
Server should start and show output. 

## Any logs, error output, etc?

```
Caught exception in terminal thread

java.io.IOException: Write end dead
	at java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.jboss.tools.intellij.rsp.util.ExecUtilClone$RedirectedStream.read(ExecUtilClone.java:65)
	at org.jboss.tools.intellij.rsp.util.ExecUtilClone$RedirectedStream.read(ExecUtilClone.java:89)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at com.jediterm.terminal.ProcessTtyConnector.read(ProcessTtyConnector.java:54)
	at com.jediterm.terminal.TtyBasedArrayDataStream.fillBuf(TtyBasedArrayDataStream.java:21)
	at com.jediterm.terminal.TtyBasedArrayDataStream.getChar(TtyBasedArrayDataStream.java:31)
	at com.jediterm.terminal.DataStreamIteratingEmulator.next(DataStreamIteratingEmulator.java:34)
	at com.jediterm.terminal.TerminalStarter.start(TerminalStarter.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:363)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrichter1** [comment] 2020-11-06 07:58
The server is actually running, even if it shows as stopped.

**Comment by robstryker** [comment] 2020-11-11 21:11
Duplicate of https://github.com/redhat-developer/intellij-rsp/issues/15

**Closed as completed by robstryker** 2020-11-11 21:11 UTC
